apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings-db
  labels:
    app: ratings-db
spec:
  selector:
    matchLabels:
      app: ratings-db
  replicas: 1
  template:
    metadata:
      labels:
        app: ratings-db
    spec:
      containers:
      - name: ratings-db
        image: postgres
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            value: password
          - name: POSTGRES_USER
            value: user123
          - name: POSTGRES_DB
            value: ratings_database