apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings
  labels:
    app: ratings
spec:
  selector:
    matchLabels:
      app: ratings
  replicas: 1
  template:
    metadata:
      labels:
        app: ratings
    spec:
      containers:
      - name: ratings
        image: gcr.io/jnp2-micrors/ratings
        ports:
        - containerPort: 80
        env:
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: user123
            - name: POSTGRES_DB
              value: ratings_database
            - name: POSTGRES_HOST
              value: ratings_db
            - name: JWT_SECRET
              value: foobar
            - name: RABBITMQ_HOST
              value: message-broker