apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  labels:
    app: users
spec:
  selector:
    matchLabels:
      app: users
  replicas: 1
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users
        image: gcr.io/jnp2-micrors/users
        ports:
        - containerPort: 80
        env:
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: user123
            - name: POSTGRES_DB
              value: user_database
            - name: POSTGRES_HOST
              value: users-db
            - name: JWT_SECRET
              value: foobar